version: '3'
services: 
     backend:   
          build: ./backend   
          restart: always 
          ports: 
          - "8000:8000"
     db:
          image: postgres:latest
          restart: always
          ports:
               - "5432:5432"
          environment:
               POSTGRES_USER: postgres
               POSTGRES_PASSWORD: postgres
               POSTGRES_DB: mods
          volumes:
               - pgdata:/var/lib/postgresql/data

     frontend:
          build: ./frontend
          restart: always
          ports:
               - "3000:3000"
          depends_on:
               - backend
volumes:
  pgdata:               